### PR TITLE
uw-ictd merge

### PR DESCRIPTION
**Pull request by ukanga**
- supports both the old and new xlsform cascades
- xlsx support among other features applied in the uw-ictd repo

### CODE REVIEW

**Comment by prabhasp** [comment]
Looks like a doozy (thanks @ukanga!). Did you run test_all_xls in formhub (after pulling in xls files from S3 into the required test folder?) @mejymejy @pld can provide more details if needed.

**Comment by mejymejy** [comment]
yeah, let me know if you need a hand or want me to check everything on my end, @ukanga

**Comment by ukanga** [comment]
@prabhasp  no i did not, those details are very welcome @mejymejy  I will need help on checking on this.

what I have been up to since yesterday is running the formhub test suite and updating fixture by fixture.

**Comment by mberg** [comment]
Yes all eyes on this please. This is a very important/big merge

**Pull request merged**
