### PR TITLE
Experimental xform xml to xform json

### PR DESCRIPTION
**Pull request by ukanga**
Given an xml xform, creates the xform json, as a result you can have a survey object for use.
Formhub plans to use this to allow xform uploads

### CODE REVIEW

**Comment by ukanga** [comment]
@nathanathan @prabhasp could you please have a look at this.

**Comment by nathanathan** [comment]
Looks good to me. Nice work! I'm curious about where how the users requesting this are creating their xforms, I.e. are they made in a text editor or another tool like odk build?

**Comment by ukanga** [comment]
I think odk build but my use case was for odk briefcase, pull and push - from online to local or vice versa.

**Comment by MartijnR** [comment]
Wow, this is big! Can't wait to try this out!

On Tue, May 14, 2013 at 10:36 AM, ukanga notifications@github.com wrote:

> I think odk build but my use case was for odk briefcase, pull and push -
> from online to local or vice versa.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/pyxform/pull/96#issuecomment-17888319
> .

## 

Enketo http://enketo.org    |    LinkedIn
http://www.linkedin.com/in/martijnvanderijdt/   |
GitHubhttps://github.com/MartijnR

**Comment by mberg** [comment]
Wait I missed this.  Does this mean we could support xform uploads in the
future for form authoring?

**Comment by ukanga** [comment]
@mberg yes.

**Pull request merged**
