### PR TITLE
Add style attribute to body tag if its specified within settings worksheet - fixes #100

### LINKED ISSUE #100: global form style
To allow form theming, right-align language, other custom form appearance, it would be great to have a form-wide appearance attribute.

Would this be a worthwhile addition to pyxforms? If so, what would be the best way to implement this, perhaps an appearance column in the settings tab and adding the appearance attribute(s) to the `<h:body>` element?

### PR DESCRIPTION
**Pull request by larryweya**

### CODE REVIEW

**Comment by larryweya** [comment]
@MartijnR Hey, sorry, I implemented as style, will change it.

**Comment by MartijnR** [comment]
Thanks! When done, could you also send a pull request to UW-ICTD?

On Mon, Oct 28, 2013 at 4:11 AM, Larry Weya notifications@github.comwrote:

> @MartijnR https://github.com/MartijnR Hey, sorry, I implemented as
> style, will change it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/pyxform/pull/103#issuecomment-27200215
> .

## 

Enketo https://enketo.org    |
LinkedInhttp://www.linkedin.com/company/enketo-llc   |
GitHub https://github.com/MartijnR

**Comment by MartijnR** [comment]
bump! Would love to get people starting to test the new grid theme next week... :)

(by entering 'theme-grid' in the style column)

**Comment by MartijnR** [comment]
Whoohooo! :+1:

**Comment by MartijnR** [comment]
@ukanga @larryweya This is not yet deployed on the Ona server, right?

**Comment by ukanga** [comment]
this should be deployed with https://github.com/onaio/onadata/pull/114

**Comment by ukanga** [comment]
I was relying on certain functionality that was added with this version, hence deployment was done quickly after the merge.

**Comment by MartijnR** [comment]
Thanks. Then something seems to not be working. I've tested with the
attached form. The XForm output has no classes added to <h:body>

On Tue, Jan 21, 2014 at 3:03 PM, ukanga notifications@github.com wrote:

> I was relying on certain functionality that was added with this version,
> hence deployment was done quickly after the merge.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SEL-Columbia/pyxform/pull/103#issuecomment-32968880
> .

## 

_Did you know that Enketo Smart Paper has now become the #1 tool for data
collection? Don't fall behind. Use it!_

Enketo https://enketo.org    |
LinkedInhttp://www.linkedin.com/company/enketo-llc   |
GitHub https://github.com/MartijnR    |    Twitterhttps://twitter.com/enketo

**Comment by ukanga** [comment]
where is the xlsform?

**Comment by ukanga** [comment]
@MartijnR the issue with your form is you used `style` instead of `class` as per you suggestion. see https://ona.io/ukanga/forms/widgets-pages/form.xml

**Comment by MartijnR** [comment]
ah yes. Sorry I meant style in XLS form should turn into the class body
attribute in XForm

Class is programmer speak. Style is better understandable to users I think.
What do you think?

On Thu, Jan 23, 2014 at 1:10 AM, ukanga notifications@github.com wrote:

> @MartijnR https://github.com/MartijnR the issue with your form is you
> used style instead of class as per you suggestion. see
> https://ona.io/ukanga/forms/widgets-pages/form.xml
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SEL-Columbia/pyxform/pull/103#issuecomment-33104350
> .

## 

_Did you know that Enketo Smart Paper has now become the #1 tool for data
collection? Don't fall behind. Use it!_

Enketo https://enketo.org    |
LinkedInhttp://www.linkedin.com/company/enketo-llc   |
GitHub https://github.com/MartijnR    |    Twitterhttps://twitter.com/enketo

**Pull request merged**
