### PR TITLE
Cleaner error message

### LINKED ISSUE #78: Better error messages for ODK validate errors
1. Cut out the everything including and follows `java.lang.NullPointerException`
2. Possibly add a link to a page that helps folks debug errors.
3. Special note, either in error itself, or in the link, that `ODK Validate Errors: Invalid XPath expression []!` means a calculate element without a calculation.
4. Back-translate `/FormName/groupname/nodename` to `${nodename}` in the error message so people can find it easier?

### PR DESCRIPTION
**Pull request by ukanga**
It resolves #78 and #84, with one exception at the moment, there is no back translation yet.

### CODE REVIEW

**Comment by prabhasp** [comment]
:+1:

**Comment by nathanathan** [comment]
We have a report on the odk issue tracker about this feature:
https://code.google.com/p/opendatakit/issues/detail?id=814

chrislrobert, the reporter, also suggested some code changes, but your branch has gotten a bit divergent. I was hoping you might have some ideas on how to handle merging the changes.

(This seems to be one of the situations where using separate repos and issue trackers is problematic.)

**Comment by ukanga** [comment]
@nathanathan could you check #95 I have included the changes. should i merge?

**Comment by nathanathan** [comment]
Sure, it looks good to me.

**Pull request merged**
