### PR TITLE
Fixed variable name: sms_allow_medias -> sms_allow_media (proper English)

### PR DESCRIPTION
**Pull request by rgaudin**
Change variable name as it's not proper English and would confuse those who know how to spell it ahah :)

@ukanga can you please merge and publish a release on pypi then let me know?

### CODE REVIEW

**Comment by rgaudin** [comment]
ah let me fix the test first.

**Comment by ukanga** [comment]
@rgaudin will wait up for the test fix.

**Comment by rgaudin** [comment]
@ukanga it's all good now.

**Comment by ukanga** [comment]
@rgaudin just deployed [v0.9.15](https://github.com/modilabs/pyxform/tree/v0.9.15) to pypi.

**Comment by rgaudin** [comment]
Awesome, thanks.

**Pull request merged**
