### PR TITLE
Instance id always added

### PR DESCRIPTION
**Pull request by mejymejy**
instance IDs! rejoice!

### CODE REVIEW

**Comment by pld** [comment]
this looks good to me.  can we add some functional tests?  after that it should be ready to merge (maybe we should also run online-xls tests, or do you guys think the changes are innocent enough?).

**Comment by prabhasp** [comment]
also, before we pull, lets make a json 'instanceID' type that is transformed in json2xform to this calculate function, rather than adding it directly. this will make it so that formhub can look at a type 'instanceID' rather than a 'calculate'. too late for nigeria forms, sadly, but stil.

**Comment by MartijnR** [comment]
https://groups.google.com/forum/?fromgroups=#!topic/opendatakit-developers/oBn7eQNQGTg and http://code.google.com/p/opendatakit/issues/detail?id=706 

It's unfortunate we have to use a calculated item for now and then change it later to a preload. Will a future pyxform change to make this a preload item, automatically update all existing forms on formhub?

**Comment by prabhasp** [comment]
The answer to your "automatic" update question: the answer is: no,
unfortunately.

**Comment by MartijnR** [comment]
Ah, that's too bad. I'm afraid implementing this as a calculated item is
going to cause us problems in the future, in particular when thinking about
the future enketo mobile client and exchanging data with the server in both
directions.

On Tue, Oct 16, 2012 at 1:06 PM, prabhasp notifications@github.com wrote:

> The answer to your "automatic" update question: the answer is: no,
> unfortunately.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/pyxform/pull/30#issuecomment-9502572.

## 

LinkedIn - www.linkedin.com/in/martijnvanderijdt/
GitHub - www.github.com/modilabs/enketo
Aid Web Solutions - www.aidwebsolutions.com

**Comment by prabhasp** [comment]
What would it take for us to implement this as a preload feature? For ODK
collect to do the same, essentially?

On Tue, Oct 16, 2012 at 3:10 PM, Martijn van de Rijdt <
notifications@github.com> wrote:

> Ah, that's too bad. I'm afraid implementing this as a calculated item is
> going to cause us problems in the future, in particular when thinking
> about
> the future enketo mobile client and exchanging data with the server in
> both
> directions.
> 
> On Tue, Oct 16, 2012 at 1:06 PM, prabhasp notifications@github.com
> wrote:
> 
> > The answer to your "automatic" update question: the answer is: no,
> > unfortunately.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/modilabs/pyxform/pull/30#issuecomment-9502572>.
> 
> ## 
> 
> LinkedIn - www.linkedin.com/in/martijnvanderijdt/
> GitHub - www.github.com/modilabs/enketo
> Aid Web Solutions - www.aidwebsolutions.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/pyxform/pull/30#issuecomment-9502708.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by MartijnR** [comment]
Not much to do in pyxform and enketo (30mins of work) and I imagine in ODK
Collect it would be equally easy (could we do this perhaps and generate a
pull request?). Maybe the more time-consuming issue is to agree to add this
new preload item to the spec.

On Tue, Oct 16, 2012 at 1:44 PM, prabhasp notifications@github.com wrote:

> What would it take for us to implement this as a preload feature? For ODK
> collect to do the same, essentially?
> 
> On Tue, Oct 16, 2012 at 3:10 PM, Martijn van de Rijdt <
> notifications@github.com> wrote:
> 
> > Ah, that's too bad. I'm afraid implementing this as a calculated item is
> > going to cause us problems in the future, in particular when thinking
> > about
> > the future enketo mobile client and exchanging data with the server in
> > both
> > directions.
> > 
> > On Tue, Oct 16, 2012 at 1:06 PM, prabhasp notifications@github.com
> > wrote:
> > 
> > > The answer to your "automatic" update question: the answer is: no,
> > > unfortunately.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/modilabs/pyxform/pull/30#issuecomment-9502572>.
> > 
> > ## 
> > 
> > LinkedIn - www.linkedin.com/in/martijnvanderijdt/
> > GitHub - www.github.com/modilabs/enketo
> > Aid Web Solutions - www.aidwebsolutions.com
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/modilabs/pyxform/pull/30#issuecomment-9502708>.
> 
> ## 
> 
> Prabhas Pokharel
> http://twitter.com/prabhasp
> US mobile: +1 347 948 7654
> skype/facebook/whatever: prabhasp
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/pyxform/pull/30#issuecomment-9503781.

## 

LinkedIn - www.linkedin.com/in/martijnvanderijdt/
GitHub - www.github.com/modilabs/enketo
Aid Web Solutions - www.aidwebsolutions.com

**Comment by larryweya** [comment]
Sorry, I'm trying to understand this, we are talking about the form's uuid,
right. If so, don't we auto generate these and send them with the form XML
- precalculated?

**Comment by MartijnR** [comment]
@larryweya, this is about the `<meta><instanceID/></meta>` which is meant to be generated on the client with the XPath uuid() function (with something like `concat('uuid:', uuid())`). So the issue is what kind of XForm binding to use in the XForm format to tell the client to do this that will work reliably in the future for both enketo, ODK Collect and any other compatible client. The proper way is using a preload item, but this won't be supported in ODK Collect for a while (unless we do it??)

P.S. I noticed there is also a `<formhub><uuid/></formhub>`, which does not relate to this (I don't know what that is used for actually). This also uses a calculate binding but without actually calculating anything on the client.

**Comment by ukanga** [comment]
UCW-ICTD/pyxform has been merged in which includes the instance id, closing this pull request

**Pull request closed without merging**
