### PR TITLE
 Added support for SMS fields

### PR DESCRIPTION
**Pull request by rgaudin**
@ukanga this is a minor change to the code since it only adds a few fields to check on and add. 

Those fields are:
`sms_id` in question list is the special id of the group.
`sms_id` in the choices WD to shortcut values (`name=1`, `sms_id=y`, `label=Yes`)
`sms_id` in the settings WS is the SMS ID/shortcut of the form
`sms_separator` is the character triggering begining of group ("+" in CC+)
`sms_allow_media` true/false whether to allow binary data (as base64)
`sms_date_format` in settings: strptime-compatible format of date input
`sms_datetime_format` in settings: strptime-compatible format of datetime input

For a more visual example, please take a look at pyxform/tests/example_xls/sms_info.xls

I think this is minor and doesn't break anything but: 
- How appropriate are those field names?
- Could'nt find proper documentation so it will probably be only documented formhub-side.

### CODE REVIEW

**Comment by ukanga** [comment]
@rgaudin 
- The field names seem appropriate to me so far; though i feel sms_keyword would have been more appropriate in settings sheet as that's what it is.
- As for documentation, i guess we could update [this google doc](https://docs.google.com/spreadsheet/ccc?key=0AgpC5gsTSm_4dDRVOEprRkVuSFZUWTlvclJ6UFRvdFE#gid=0) if we have access.

**Comment by rgaudin** [comment]
@ukanga OK I changed it to `sms_keyword` which, you're right, is more appropriate.
As per the google doc, I don't have access ; who owns it?

**Comment by prabhasp** [comment]
On Wed, Mar 27, 2013 at 7:42 AM, rgaudin notifications@github.com wrote:

> @ukanga https://github.com/ukanga OK I changed it to sms_keyword which,
> you're right, is more appropriate.
> As per the google doc, I don't have access ; who owns it?
> 
> That document is
> jointly owned between UW_ICTD (the ODK guys) and us. We haven't talked
> about this to them, so can we start by adding the information here (
> https://docs.google.com/spreadsheet/ccc?key=0AqkhmY48RtzudHJWR1UycEUwVk5rUzJsTmkyaThlMFE#gid=0
> ); Renaud, you have been given write access. We can have a call with them
> in a couple of weeks, once we are absolutely solid on the keyword etc.
> structure, maybe have tested it out a bit, and then bring it to the general
> XLSform standard.

Does that work?

>  —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/pyxform/pull/88#issuecomment-15518818
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by rgaudin** [comment]
@prabhasp OK didn't realize it was not modilabs only. As proposed, I suggest we merge this and once we have a solid, tested and adjusted implementation of SMS, we can contact them.

**Pull request merged**
